name: Build macOS App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        # Try the mac-specific requirements first, fall back to a more flexible approach if needed
        if [ -f mac-requirements.txt ]; then
          pip install -r mac-requirements.txt
        else
          # Install tensorflow and other key packages
          pip install tensorflow opencv-python numpy pillow pyside6
          # Try to install other packages flexibly
          cat requirements.txt | grep -v "tensorflow-io-gcs-filesystem" | xargs pip install --no-deps || true
        fi
    - name: Build with PyInstaller
      run: |
        # Replace with your actual main script name
        pyinstaller --onefile main.py
    - name: Upload macOS build
      uses: actions/upload-artifact@v4
      with:
        name: macos-app
        path: dist/