name: Build macOS App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        # Try the mac-specific requirements first, fall back to a more flexible approach if needed
        if [ -f mac-requirements.txt ]; then
          pip install -r mac-requirements.txt
        else
          # Install tensorflow and other key packages
          pip install tensorflow opencv-python numpy pillow pyside6
          # Try to install other packages flexibly
          cat requirements.txt | grep -v "tensorflow-io-gcs-filesystem" | xargs pip install --no-deps || true
        fi
    - name: Build with PyInstaller
      run: |
        # Create a macOS .app bundle instead of a plain executable
        pyinstaller --clean --windowed --name "ThumbnailGenerator" --osx-bundle-identifier=com.yourcompany.thumbnailgenerator main.py
        # Make sure the app is executable
        chmod +x dist/ThumbnailGenerator.app/Contents/MacOS/ThumbnailGenerator
        # Create a zip of the .app bundle to preserve permissions
        cd dist && zip -r ThumbnailGenerator.app.zip ThumbnailGenerator.app && cd ..
    - name: Upload macOS build
      uses: actions/upload-artifact@v4
      with:
        name: macos-app
        path: |
          dist/ThumbnailGenerator.app.zip
          dist/ThumbnailGenerator.app